ALTER TABLE sessions ADD COLUMN IF NOT EXISTS visitor_id VARCHAR(255);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS country VARCHAR(8);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS browser VARCHAR(64);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS os VARCHAR(64);
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS referrer TEXT;
